// Equipos
let teams = {
    cai: {
        name: 'Independiente de Cosquín',
        alias:  'CAI',
        dt: {
            lname: 'Viva',
            fname: 'Pablo',
        },
    },
    tsc: {
        name: 'Chelcas',
        alias:  'TSC',
        dt: {
            lname: 'Frid',
            fname: 'Danilo Ronán',
        },
    },
    hc: {
        name: 'Hindú Club',
        alias:  null,
        dt: {
            lname: 'LOPEZ',
            fname: 'ARIEL GERMAN',
        },
    },
    pl: {
        name: 'Poeta Lugones',
        alias:  null,
        dt: {
            lname: 'DALLA RIVA',
            fname: 'GUSTAVO DAVID',
        },
    },
};


// Jugadoras
let players = {
    'player1':{ lname: 'Alabart', fname: 'Eugenia', shirt: null, height: null, team: teams.cai, foto: 'media/img/jugadora-.jpeg', },
    'player2':{ lname: 'Astray', fname: 'Laura', shirt: null, height: null, team: teams.cai, foto: 'media/img/jugadora-.jpeg', },
    'player3':{ lname: 'Astray', fname: 'Noelia', shirt: null, height: null, team: teams.cai, foto: 'media/img/jugadora-.jpeg', },
    'player4':{ lname: 'Borri', fname: 'Soledad', shirt: null, height: null, team: teams.cai, foto: 'media/img/jugadora-.jpeg', },
    'player5':{ lname: 'Fernandez', fname: 'Belén', shirt: null, height: null, team: teams.cai, foto: 'media/img/jugadora-.jpeg', },
    'player6':{ lname: 'Garcia', fname: 'Ana Laura', shirt: null, height: null, team: teams.cai, foto: 'media/img/jugadora-.jpeg', },
    'player7':{ lname: 'Garmendia', fname: 'Noelia', shirt: null, height: null, team: teams.cai, foto: 'media/img/jugadora-.jpeg', },
    'player8':{ lname: 'Godoy', fname: 'Natalia', shirt: null, height: null, team: teams.cai, foto: 'media/img/-jugadora-.jpeg', },
    'player9':{ lname: 'Guzman', fname: 'Silvina', shirt: null, height: null, team: teams.cai, foto: 'media/img/-jugadora-.jpeg', },
    'player10':{ lname: 'Sanchez', fname: 'Lorena', shirt: null, height: null, team: teams.cai, foto: 'media/img/-jugadora-.jpeg', },
    'player11':{ lname: 'Vilchez', fname: 'Melisa', shirt: null, height: null, team: teams.cai, foto: 'media/img/-jugadora-.jpeg', },
    'player12':{ lname: 'Vitullo', fname: 'Natalia', shirt: null, height: null, team: teams.cai, foto: 'media/img/-jugadora-.jpeg', },
    'player13':{ lname: 'Zamboni', fname: 'Belén', shirt: null, height: null, team: teams.cai, foto: 'media/img/-jugadora-.jpeg', },
    'player14':{ lname: 'GAZULLA', fname: 'LINIANA INES', shirt: 14, height: 1.70, team: teams.tsc, foto: 'media/img/-jugadora-.jpeg', },
    'player15':{ lname: 'VALLE', fname: 'SANDRA MARIEL', shirt: 9, height: 1.65, team: teams.tsc, foto: 'media/img/-jugadora-.jpeg', },
    'player16':{ lname: 'CHARLIER', fname: 'MARIA PATRICIA', shirt: 8, height: 1.58, team: teams.tsc, foto: 'media/img/-jugadora-.jpeg', },
    'player17':{ lname: 'KARLEN SANTILLAN', fname: 'MICAELA PAULA', shirt: null, height: 1.61, team: teams.tsc, foto: 'media/img/-jugadora-.jpeg', },
    'player18':{ lname: 'ARIAS', fname: 'MARIA EMILIA', shirt: 84 / 11, height: 1.57, team: teams.tsc, foto: 'media/img/-jugadora-.jpeg', },
    'player19':{ lname: 'FERNANDEZ', fname: 'MARIA', shirt: 20, height: 1.52, team: teams.tsc, foto: 'media/img/-jugadora-.jpeg', },
    'player20':{ lname: 'BORTOLI', fname: 'MARIA LAURA', shirt: null, height: 1.70, team: teams.tsc, foto: 'media/img/-jugadora-.jpeg', },
    'player21':{ lname: 'AVILA', fname: 'ANDREA CONSTANZA', shirt: 5, height: 1.50, team: teams.tsc, foto: 'media/img/-jugadora-.jpeg', },
    'player22':{ lname: 'BARRETO', fname: 'MERCEDES VALERIA', shirt: 6, height: 1.60, team: teams.tsc, foto: 'media/img/-jugadora-.jpeg', },
    'player23':{ lname: 'LEDESMA', fname: 'ANABEL ANDREA', shirt: null, height: 1.67, team: teams.tsc, foto: 'media/img/-jugadora-.jpeg', },
    'player24':{ lname: 'BERRA', fname: 'AYLEN DANIELA', shirt: null, height: 1.70, team: teams.tsc, foto: 'media/img/-jugadora-.jpeg', },
    'player25':{ lname: 'ARIAS', fname: 'YANINA IVANA', shirt: null, height: null, team: teams.tsc, foto: 'media/img/-jugadora-.jpeg', },
    'player26':{ lname:  'TORAL', fname: 'MARIA MACARENA', shirt: 1, height: 1.68, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player27':{ lname:  'NATALI', fname: 'ALICIA', shirt:  1, height: 1.75, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player28':{ lname:  'CAGNOLO', fname: 'CARLA VERONICA', shirt: 1, height: 1.58, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player29':{ lname:  'ZABALA', fname: 'MARIA LAURA', shirt: 8, height: 1.63, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player30':{ lname:  'MORENO', fname: 'JULIETA VANESA', shirt: 6, height: 1.72, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player31':{ lname:  'CIA', fname: 'ANA LAURA', shirt: 4, height: 1.73, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player32':{ lname:  'CASANOVA', fname: 'INES ELIZABETH', shirt:  1, height: 1.69, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player33':{ lname:  'ARTAZA', fname: 'YUDITH', shirt: 7, height: 1.64, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player34':{ lname:  'BRITOS', fname: 'MARIA LUZ', shirt: 1, height: 1.74, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player35':{ lname:  'GARCIA', fname: 'NATALIA', shirt: 1, height: 1.56, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player36':{ lname:  'HERNANDEZ', fname: 'MARIELA CRISTINA', shirt:  9, height: 1.63, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player37':{ lname:  'SINTORA', fname: 'MARIA SOL', shirt: 5, height: 1.66, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player38':{ lname:  'SANRRAME', fname: 'NOELIA', shirt: null, height: 1.63, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player39':{ lname:  'CORONEL', fname: 'CONSUELO', shirt: null, height: 1.69, team: teams.hc, foto: 'media/img/-jugadora-.jpeg', },
    'player40':{ lname:  'Moyano', fname: 'Carolina Evelin', shirt: 0, height: 1.66, team: teams.pl,foto: 'media/img/-jugadora-.jpeg', },
    'player41':{ lname:  'Ahumada', fname: 'Claudia Elizabeth', shirt: 5, height: 1.70, team: teams.pl, foto: 'media/img/-jugadora-.jpeg', },
    'player42':{ lname:  'Choque', fname: 'Leonor Marcela Luján', shirt: 9, height: 1.57, team: teams.pl, foto: 'media/img/-jugadora-.jpeg', },
    'player43':{ lname:  'Rivero', fname: 'Yanina Alejandra', shirt: 14, height: 1.74, team: teams.pl, foto: 'media/img/-jugadora-.jpeg', },
    'player44':{ lname:  'Aurispa', fname: 'Maria Florencia', shirt: 17, height: 1.60, team: teams.pl, foto: 'media/img/-jugadora-.jpeg', },
    'player45':{ lname:  'González', fname: 'María Inés', shirt: 16, height: null, team: teams.pl, foto: 'media/img/-jugadora-.jpeg', },
    'player46':{ lname:  'Zarranz', fname: 'Agostina', shirt: 10, height: 1.70, team: teams.pl, foto: 'media/img/-jugadora-.jpeg', },
    'player47':{ lname:  'Juárez', fname: 'Natalia Vanessa', shirt: 22, height: 1.73, team: teams.pl, foto: 'media/img/-jugadora-.jpeg', },
    'player48':{ lname:  'Donda',  fname: 'Paula', shirt: 24, height: 1.58, team: teams.pl, foto: 'media/img/-jugadora-.jpeg', },
    'player49':{ lname:  'Bustos', fname: 'Gabriela', shirt: 46, height: 1.68, team: teams.pl, foto: 'media/img/-jugadora-.jpeg', },
    'player50':{ lname:  'Bertola', fname:'Melisa', shirt: 32, height: null, team: teams.pl, foto: 'media/img/-jugadora-.jpeg', },
};
